### ISSUE TITLE
values not increasing or decreasing

### ISSUE THREAD

**Issue by oliv98** [SAMUD/KISS-OSD#11]
Hi, I have an issue with roll stick in the menus. For some settings I cannot increase or decrease value.
for example
 - Happens for capacity second warning.I can only decrease
- Happens for min per cell volt. I can only increase.

thanks for your time programming for our pleasure

**Comment by SAMUD** [comment]
@oliv98 Strange... I will take a look into this. Thanks for submitting

**Comment by SAMUD** [comment]
Please reinstall your OSD., cause something went wrong. For me all is working
