### ISSUE TITLE
Letters in top are outside screen on micro minimosd

### ISSUE THREAD

**Issue by RobbieHood** [SAMUD/KISS-OSD#12]
I have flashed this firmware to my micro minimosd and noticed the letters on the top of the display are outisde the screen.

**Comment by SAMUD** [comment]
@RobbieHood When exactly are the letters outside of the screen? In the menu or in the normal view?
Can you say me what exactly is out of the screen and if a whole row is missing or only some pixels?

**Comment by RobbieHood** [comment]
It happens in the normal view and the whole top row shows only the bottom
half of the letters.

See attached picture.

**Comment by RobbieHood** [comment]
[![20161128_113231.jpg](https://s22.postimg.org/6x1r2hm9d/20161128_113231.jpg)](https://postimg.org/image/bixvau7sd/)

**Comment by SAMUD** [comment]
@RobbieHood .Never heard of this. Also it is really strange that you only have this problem on the main screen and not in the menu.

I will try to add a calibration to the menu so you can calibrate down some pixels. 

Just another question: Did you tried to run any other OSD-SW for example mw-osd or the official flyduino one?

**Comment by RobbieHood** [comment]
Only just recently moved to KISS from betaflight. Been running mwosd for a long time now on betaflight and others and never had an issue.

**Comment by SAMUD** [comment]
@RobbieHood OK. In the meanwhile, until I make the calibration, you can adjust the first line manually. 
If you don't know how to do it I can do it for you rapidly

**Comment by RobbieHood** [comment]
Dont worry I should be able too once I have time to get to my machine.

**Comment by SAMUD** [comment]
@RobbieHood Perfect

**Comment by SAMUD** [comment]
@RobbieHood bug fixed.
Later there will be an official release.
