### ISSUE TITLE
EEPROM Not Declared Error message

### ISSUE THREAD

**Issue by mgalimbe** [SAMUD/KISS-OSD#17]
when compiling the kiss osd 5.3.3 sketch using the micro minim osd I got this EEPROM error message
EEPROM was not declared in this scope. Here is the actual code:

	EEPROM.setMemPool(32, EEPROMSizeATmega328);

**Comment by mgalimbe** [comment]
I figured it out I had to copy the library folder to Arduino. then it worked fine. Having an issue navigating the menu on my fat shark goggles though.

**Comment by SAMUD** [comment]
@mgalimbe Which Arduino version are you using? Did you copy EEPROMex into your libraries? Do you have the file Global.h in the unzipped folder?

Normally you shouldn't have this error.
You can also try to redownload the package.

**Comment by mgalimbe** [comment]
Thanks samud. The osd menu doesn't respond to the yaw command sometimes and what is with the calibrating gyro at startup. It takes a long while to complete.

**Comment by SAMUD** [comment]
@mgalimbe Yeah. That's a known bug. With the latest version of the Kiss FC the communication between both devices fails sometimes. I'm working on a fix already.
If you have Facebook you can join this group:
 https://m.facebook.com/groups/1624296364543353

There is a post with some intermediate methods to fix this problem until I found a correct fix.

**Comment by mgalimbe** [comment]
You're the best man! Thank you for the great osd program.  I will join your fb group.

**Comment by SAMUD** [comment]
@mgalimbe Thank you :)
