### ISSUE TITLE
Kiss 1.3 compatibility

### ISSUE THREAD

**Issue by gregorg** [SAMUD/KISS-OSD#20]
> New kiss protocol CRC support (Kiss osd should work fine, Third party OSDs are also in process of changing)

https://www.rcgroups.com/forums/showthread.php?2555204-KISS-FC-Flyduino-32bit-Flightcontroller/page416&perpage=50#post37618662

**Comment by SAMUD** [comment]
Thanks for the Information.  👍 

By chance I already saw it some days ago and already implemented it. 
First beta is out since yesterday :)

**Comment by gregorg** [comment]
Excellent :+1:
