### ISSUE TITLE
Add Low Battery warning

### ISSUE THREAD

**Issue by oliv98** [SAMUD/KISS-OSD#5]
Hi Guys, what would be nice is to have a "Low Battery" warning message flashing a little bit under the center of the screen. From my experience, the flashing voltage in lower left corner is not enough, and may be even unnoticed because the eye is focussing on the center of the screen. I did lost a battery because of that
thanks for your work toward the community

**Comment by SAMUD** [comment]
@oliv98 Samuel Daurat:
Oh sh**....

To be honest I already thought of making a 2 stage alarm with a text message when It gets really critical. 
As soon as I have some time I will add it.

**Comment by SAMUD** [comment]
Just released V4 with 2nd stage voltage alarm.
