### ISSUE TITLE
Wrong filename #include Max7456.h

### ISSUE THREAD

**Issue by a-t-a-r-i** [SAMUD/KISS-OSD#6]
Hi,
with Linux it is not possible to compile the Code. 

> /opt/arduino-1.6.10/libraries/MAX7456/MAX7456.cpp:28:23: fatal error: Max7456.h: No such file or directory
>    #include "Max7456.h"
>                        ^
> compilation terminated.

Linux Filenames are Case sensitive. 

Problem:  `#include "Max7456.h` !=  `#include "MAX7456.h"`

Solution:

Change Line 28 in MAX7456.cpp to `#include "MAX7456.h"`

**Comment by SAMUD** [comment]
@a-t-a-r-i Oh, thank you for this hint. I will change this.
