### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by gearwolf-OP** [SAMUD/KISS-OSD#8]
When trying to compile:

EEPROM_Handling.ino: In function 'void EEPROMinit()':
EEPROM_Handling:4: error: 'EEPROM' was not declared in this scope
EEPROM_Handling:4: error: 'EEPROMSizeATmega328' was not declared in this scope
EEPROM_Handling.ino: In function 'bool EEPROMloadConfig()':
EEPROM_Handling:28: error: 'EEPROM' was not declared in this scope
EEPROM_Handling.ino: In function 'void EEPROMsave()':
EEPROM_Handling:53: error: 'EEPROM' was not declared in this scope
EEPROM_Handling.ino: In function 'void EEPROMinit()':
EEPROM_Handling:4: error: 'EEPROM' was not declared in this scope
EEPROM_Handling:4: error: 'EEPROMSizeATmega328' was not declared in this scope
EEPROM_Handling.ino: In function 'bool EEPROMloadConfig()':
EEPROM_Handling:28: error: 'EEPROM' was not declared in this scope
EEPROM_Handling.ino: In function 'void EEPROMsave()':
EEPROM_Handling:53: error: 'EEPROM' was not declared in this scope

**Comment by SAMUD** [comment]
@gearwolf-OP Hoppla. You tried to compile one of the releases or the actual projec?

**Comment by SAMUD** [comment]
@gearwolf-OP The thing which is strange it is that it wanted to compile "EEPROM[space]handling". But the file name is "EEPROM_Handling"
Edit: OK. Now in github on the PC it shows me the underscore. On my phone it replaced it with a space.

Please double check that you really downloaded the latest version (5.1 or 5.2) or that you used directly the code on github and that you copied the libraries into the libraries folder. Also I forgot to change something in the wiki. You need to copie also the EEPROM librari. I will update the wiki in the next 5 minutes.

**Comment by gearwolf-OP** [comment]
I tried to compile the 5.2 release from the download section.  I have the EEPROM library installed.  I also tried to copy the EEPROM library to the libraries folder in the KISS-OSD 5.2 folder to see if it would work but it didn't.  Still the same error.  Do I need the V2 of the EEPROM library to make it work?

**Comment by SAMUD** [comment]
@gearwolf-OP Have you tried to redownload all the files? And are your running on Arduino 1.0.5 or another Version?

**Comment by gearwolf-OP** [comment]
I'm running Arduino 1.0.5 rc2 and have redownloaded all the files to make sure.  Still same issue

**Comment by gearwolf-OP** [comment]
Ah ok I messed up.  I thought you were talking about the installed EEPROM library.  I copied over the one in the source file and it uploaded just fine.  I just am having issues now with the osd freezing.  It's stuck on wait disarmed.  Even if I arm the board it won't change the settings.

**Comment by SAMUD** [comment]
@gearwolf-OP When does it freeze and what else is written in the middle of the screen? Do you get other values like the voltage?

**Comment by gearwolf-OP** [comment]
I can get every parameter on the screen but its frozen on start up.  The Disarmed Warning is in the front but won't go away and a wait don't arm 0 message above it.  Could it be that I shouldn't be using this firmware with a PiggyOSD.  I thought they shared the same hardware, but I could be wrong.

**Comment by gearwolf-OP** [comment]
Tried it on a regular minimosd and it works great.  The piggyosd is still freezing.  Looking at the chips the differences are Minimosd has the large chip with an NBU of 1523 and the piggyosd has with the same chip an nbu of 1630.  The small chip on the minimosd has a mu1521 china-b A3JFJA and on the piggyosd mu1624 china-b A87WKA.

**Comment by gearwolf-OP** [comment]
So......I'm really sorry for making this an "Issue"  Seems the diagram on the piggyosd shows what should be the correct wire placement TX-->RXOSD and RX-->TXOSD however when I reversed them just because I thought I had no other choice pairing TX-->TXOSD and RX-->RXOSD it worked.  Again sorry for thinking you had issues with the firmware.  I really like it especially paired with the PiggyOSD which is essentailly a minimosd on a single sided board with hole patterns for the hS1177 and hs1190 camera.   Thank you SAMUD for helping me out.  Sorry for the confusion.

**Comment by SAMUD** [comment]
@gearwolf-OP No Problem. :) 
Yeah in my second quad I also wanted to mount the piggy osd, but at that time nobody had it in stock. No I'm running with the normal osd.
